config/routes.rb
Rails.application.routes.draw do

  get 'relationships/create'

  get 'relationships/destroy'

  get 'facebook/iine'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  get 'facebooks' => 'facebooks#index'

  resources :facebooks do
    #urlはfacebook_id/commentsとなる
    resources :comments
    post :confirm, on: :collection
  end

  resources :conversations do
    #urlはonversation/conversation_id/messageとなる
    resources :messages
  end

  resources :users, only: [:index]
  resources :relationships, only: [:create, :destroy]

  root 'facebooks#index'
  #root 'top#index'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/facebook.rb
class Facebook < ActiveRecord::Base
  validates :title, :content, presence: true
  belongs_to :user
  has_many :comments, dependent: :destroy
  mount_uploader :content_image, ContentImageUploader
end

app/controllers/facebooks_controller.rb
class FacebooksController < ApplicationController
  before_action :set_facebook, only: [:edit, :update, :destroy, :show]
  before_action :set_current_user_image, only: [:index, :edit, :show]
  before_action :authenticate_user!
  def index
    @facebooks = Facebook.all.order("updated_at DESC")
    @facebook = Facebook.new
    @comment = @facebook.comments.build
    @comments = @facebook.comments
    @user = User.all
  end

  def new
  end

  def create
    @facebook = Facebook.new(facebooks_params)
    @facebook.user_id = current_user.id

    if @facebook.save
      redirect_to root_path, notice: "投稿しました！"
      NoticeMailer.sendmail_facebook(@facebook).deliver
    else
      redirect_to root_path, flash: { error: @facebook.errors.full_messages }
    end
  end

  def edit

  end

  def confirm
     @facebook = Facebook.new(facebooks_params)
  end

  def show
    @comment = @facebook.comments.build
    @comments = @facebook.comments
  end


  def update
    if @facebook.update(facebooks_params)
      redirect_to root_path, notice: "投稿内容を更新しました！"
    else
      render 'edit'
    end
  end

  def destroy
    @facebook.destroy
    redirect_to root_path, notice: "投稿内容を削除しました！"
  end

  private
    def facebooks_params
      #画像がアップロードできるようになったらpermitにimage_urlを追加する
      params.require(:facebook).permit(:content,:title, :content_image)
    end

    def set_facebook
      @facebook = Facebook.find(params[:id])
    end

    def set_current_user_image
      @current_user = current_user
    end
end

app/helpers/facebooks_helper.rb
module FacebooksHelper
end

app/views/facebooks/_header.html.erb
<header>
  <ul>
    <li><%= link_to image_tag('fLogo.png', { :alt => 'Facebookのロゴ', :size => "40x40"}), root_path %></li>
    <% if user_signed_in? %>
      <li>
      <!-- 検索ボタンの引用元-->
      <!--https://www.w3schools.com/bootstrap/bootstrap_navbar.asp -->
      <div class="wrapper col-xs-4 col-sm-6 col-md-8">
      <form class="navbar-form navbar-left">
        <div class="input-group">
          <input type="text" class="form-control" size="60" placeholder="友達、スポット等を検索">
          <div class="input-group-btn">
            <button class="btn btn-default" type="submit">
              <i class="glyphicon glyphicon-search"></i>
            </button>
          </div>
        </div>
      </form>
    </div>
    <li><%= link_to login_user_img(@current_user), edit_user_registration_path %></li>
    <li><%= link_to "ホーム", root_path %></li>
    <li><%= link_to "友達を検索", root_path %></li>
    <li><%= link_to 'ユーザー一覧', users_path if user_signed_in? %></li>
    <li><%= link_to "メッセージ", conversations_path %></li>
    <li><%= link_to image_tag('people.jpg', { :alt => '友達リクエスト', :size => "30x30"}), root_path %></li>
    <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to 'ログイン', new_user_session_path %></li>
      <li><%= link_to 'サインアップ', new_user_registration_path %></li>
    <% end %>
  </ul>
</header>

app/views/facebooks/confirm.html.erb
<h3>以下の内容で、投稿する。</h3>

<%= form_for(@facebook) do |f| %>
  <%= f.hidden_field :title %>
  <%= f.hidden_field :content %>
  <%= f.hidden_field :content_image %>

  <p>タイトル:<%= @facebook.title %></p>
  <p>本文:<%= @facebook.content %></p>
  <% unless f.content_image.nil?%>
    <%= image_tag(f.content_image, alt: '投稿写真',:size => "300x300") %>
  <% end %>
  <%= f.submit "投稿する" %>
<% end %>

app/views/facebooks/edit.html.erb
<%= render 'header'%><br><br><br><br>
<div class="child row">
  <div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
<h1>編集画面</h1>
<%= form_for(@facebook) do |f| %>
  <% if @facebook.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @facebook.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <br>
  <%= f.label :content_image %>
  <%= f.file_field :content_image %>
  <br>
  <%= f.submit %>
<% end %>

<%= link_to "トップへもどる", root_path %>

<div>
</div>

app/views/facebooks/iine.js.erb
$('#fuga-dtl').html('<%= j(render("fuga_dtl")) %>');

app/views/facebooks/index.html.erb
<!-- 参考ページhttp://algo13.net/bootstrap/affix.html-->
<html>
  <head>
    <script src="https://code.jquery.com/jquery-3.1.0.slim.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script>
    (function(window, $) {
      'use strict';
      $(function() {
        var m = $('#main');
        // スクロール位置と連動させない場合は不要(scrollspy用)
        $(document.body).scrollspy({ target: '.algo13-sidebar' });
        // スクロール位置と連動させない場合は不要(scrollspy用)
        $(window).on('load', function() { $(document.body).scrollspy('refresh') });
        // 固定サイドバーのスクロール追従開始＆終了位置の設定(affix用)
        setTimeout(function() {
          $('.algo13-sidebar').affix({
            offset: {
              top: function() {
                return (this.top = m.offset().top);
              }
            }
          })
        }, 100);
      });
    })(window, jQuery);
    </script>
  </head>
  <body>
    <%= render 'header' %><br><br><br>
    <% if user_signed_in? %>
        <div class = "row">
          <div class="col-xs-2" style="background:#CCC;">
            <center>
            <p><%= link_to profile_img(@current_user), edit_user_registration_path %><%= @current_user.name%></p>
            <p><%= link_to 'ニュースフィールド'%><p>
            <p><%= link_to 'Messanger'%><p>
            <h5>発見</h5>
            <p><%= link_to 'イベント'%><p>
            <p><%= link_to 'Facebookページ'%><p>
            <p><%= link_to 'グループ'%><p>
            <p><%= link_to '友達リスト'%><p>
            <p><%= link_to 'インサイト'%><p>
            <p><%= link_to 'ゲーム'%><p>
            <p><%= link_to 'ライブ動画'%><p>
            <p><%= link_to '過去のこの日'%><p>
            <p><%= link_to 'Poke'%><p>
            <p><%= link_to 'ゲームフィールド'%><p>
            <p><%= link_to 'もっと見る...'%><p>
            <h5>作成</h5>
            <p>
              <%= link_to '広告'%>
              <%= link_to 'ページ'%>
              <%= link_to 'グループ'%>
              <%= link_to 'イベント'%>
            <p>
            </center>
          </div>
          <div class="col-xs-6" style="background:#CCC;">
            <div class="panel panel-default">
							<p id="notice"><%= notice %></p>
							<div class="panel-heading">
								<p>ステータス<p></div>
									<%= form_for(@facebook) do |f| %>
									<div class="panel-body"><br>
										<%= f.text_area :title, :size=>"40x1", placeholder: "タイトルを入力してください" %><br>
										<%= f.text_area :content, :size=>"60x5", placeholder: "今なにしてる？" %>
										<% if flash[:error].present? %>
										<ul class="errors">
											<% flash[:error].each do |msg| %>
											<li><%= msg %></li>
											<% end %>
										</ul>
										<% end %>
									</div>
									<div class="panel-footer">
										<%= f.file_field :content_image %>
										<%= f.submit "投稿する"%>
									</div>
									<% end %>
								</div>
                <div id="main"></div>
                <% @facebooks.each do |facebook| %>
								<div class="panel panel-default">
									<div class="panel-heading">
										<%= profile_img(facebook.user) %><br>
										<%= facebook.user.name%>さんが投稿しました。 最終更新日：<%= facebook.updated_at %>
									</div>
									<div class="panel-body">
										<h4>タイトル：
											<%= link_to facebook_path(facebook) do %>
											<%= facebook.title %>
											<% end %>
										</h4><br>
										<p>コメント：
											<%= facebook.content %>
										</p><br>
										<% unless facebook.content_image.blank?%>
										<%= image_tag(facebook.content_image, alt: '投稿写真',:size => "600x600") %>
										<% end %>
									</div>
									<div class="panel-footer">
										<%= form_tag({controller: "facebook", action: "iine"}, {data: {remote: true}}) do %>
										<%= submit_tag("いいね", name: nil) %>
										<% end %>
										<br>
										<%= link_to "編集", edit_facebook_path(facebook.id), class: 'btn btn-default btn-sm btn-success' %>
										<%= link_to "削除", facebook_path(facebook.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-default btn-sm btn btn-danger' %>
									</div>
								</div>
								<% end %>
          </div>
          <div class="col-xs-4" style="background:#CCC;">
              <nav class="algo13-sidebar hidden-print"><!-- hidden-xs -->
                <ul class="nav">
                  <li>
                    <h5>今日はFecebookさんの誕生日です。</h5>
                  </li>
                  <p>友達リクエスト</p>
  								<% @user.first(6).each do |user| %>
  								<%= link_to profile_img(user) %>
  								<%= user.name %><br>
  								<button class="btn btn-default button" type="submit">
  									<font size="1">友達リクエストを承認</font>
  								</button><br>
  								<% end %><br>
                </ul>
              </nav>
        </div>
    <% end %>
  </body>
</htmL>

app/views/facebooks/show.html.erb
    <%= render 'header' %><br><br><br>
    <p id="notice"><%= notice %></p>
    <div class="child row">
      <div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <div class="facebook-text">
      <p class="message_left"><strong>タイトル</strong></p>
      <p class="message_left"><%= @facebook.title %></p>
      <p class="message_left"><strong>内容</strong></p>
      <p class="message_left"><%= @facebook.content %></p>
      <p class="right">
        <strong>作成時間:</strong>
        <%= @facebook.created_at.strftime("%y/%m/%d %p %l:%M") %>
      </p>
    </div>
    <p>コメント一覧</p>
    <div id="comments_area">
      <%= render partial: 'comments/index', locals: { comments: @comments, facebook: @facebook } %>
    </div>
    <%= render partial: 'comments/form', locals: { comment: @comment, facebook: @facebook } %>
    <% if current_user.id == @facebook.user_id %>
      <%= link_to '編集', edit_facebook_path(@facebook) %>
    <% end %>
    <%= link_to '戻る', root_path %>
  </div>
</div>