config/routes.rb
Rails.application.routes.draw do

  get 'relationships/create'

  get 'relationships/destroy'

  get 'facebook/iine'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  get 'facebooks' => 'facebooks#index'

  resources :facebooks do
    #urlはfacebook_id/commentsとなる
    resources :comments
    post :confirm, on: :collection
  end

  resources :conversations do
    #urlはonversation/conversation_id/messageとなる
    resources :messages
  end

  resources :users, only: [:index]
  resources :relationships, only: [:create, :destroy]

  root 'facebooks#index'
  #root 'top#index'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, presence: true
  belongs_to :user
  belongs_to :facebook
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:edit, :destroy, :update,:show]
  def create
    @comment = current_user.comments.build(comment_params)
    @facebook = @comment.facebook


    respond_to do |format|
      #binding.pry
      if @comment.save
        format.html { redirect_to facebook_path(@facebook), notice: 'コメントを投稿しました。' }
        format.js { render :index }
      else
        #binding.pry
        format.html { redirect_to facebook_path(@facebook), notice: 'コメント投稿失敗'  }
        flash.now[:notice] = 'コメント送信失敗'
        format.js { render :index }

      end
    end
  end

  def edit
    #どのブログの情報かを取得。
    @facebook = @comment.facebook
  end

  def update
    if @comment.update(comment_params)
      redirect_to facebook_path(@comment.facebook), notice: "コメントを更新しました"
    else
      render 'index'
    end
  end

  def show
    @facebook = @comment.facebook
    render 'index'
  end

  def destroy
    @comment.destroy
    flash.now[:message] = "コメントを削除しました！"
    #renderで非同期通信となる
    render 'index'
  end

  private
    # ストロングパラメーター
    def comment_params
      params.require(:comment).permit(:facebook_id, :content)
    end

    def set_comment
      #ブログのどのコメントの情報かを取得する
      @comment=Comment.find(params[:id])
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([facebook,comment], remote: true) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :facebook_id %>
  <div class="field">
    <%= f.text_field :content, placeholder: "内容", class: "form-control"  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<%= notice %>
<ul>
  <% comments.each do |comment| %>
    <% unless comment.id.nil? %>
      <li>
        <p class="comment_left"><%= comment.user.name %>さんがコメントしました。</p>
        <p class="comment_left"><%= comment.content %></p>
        <% if current_user.id == comment.user.id %>
          <p class="right">
            <%= link_to '', edit_facebook_comment_path(facebook, comment), class: "fa fa-pencil-square-o fa-lg" %>
            <%= link_to '', facebook_comment_path(facebook, comment), class: "fa fa-trash-o fa-lg", method: :delete, remote: true, data: { confirm: '本当に削除していいですか？' } %>
          </p>
        <% end %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/comments/edit.html.erb
<h2>編集画面</h2>
<div class="container">
    <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
      <% if @comment.errors.any? %>
        <div id="error_explanation" class="alert alert-danger">
          <ul>
            <% @comment.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= render partial: 'comments/form', locals: { comment: @comment, facebook: @facebook } %>
  </div>
</div>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.facebook.comments, facebook: @comment.facebook }) %>")
$(':text').val('')